minVersion: "0.20.0"

github:
  owner: getsentry
  repo: cdc
# TODO: Add a changelog
changelogPolicy: none

artifactProvider:
  name: none
statusProvider:
  name: github

preReleaseCommand: ''

targets:
  - name: github
  - id: release
    name: docker
    source: us.gcr.io/sentryio/cdc
    target: getsentry/cdc
  - id: latest
    name: docker
    source: us.gcr.io/sentryio/cdc
    target: getsentry/cdc
    targetFormat: '{{{target}}}:latest'
