# Sentry releases
# sentry:
#   organization: sentry
#   project: cdc
#   repository: getsentry/cdc

kubernetes:
  credentials:
    kind: gcloud
    project: internal-sentry
    cluster: primary
    zone: us-central1-b

steps:
- kind: KubernetesDeployment
  selector:
    label_selector: service=cdc
  containers:
  - image: us.gcr.io/internal-sentry/github_getsentry_cdc:{sha}
    name: producer
