# Sentry releases
# sentry:
#   organization: sentry
#   project: cdc
#   repository: getsentry/cdc

steps:
- kind: KubernetesDeployment
  selector:
    label_selector: service=cdc
  containers:
  - image: us.gcr.io/internal-sentry/github_getsentry_cdc:{sha}
    name: producer
