services:
  - docker

before_install:
  - sudo service postgresql stop

install:
  - docker run -d --net host --name postgres $(docker build -q .travis/postgres) -c wal_level=logical -c max_replication_slots=1 -c max_wal_senders=1
  - docker logs postgres
  - docker build -t getsentry/cdc --target development .
  - docker exec postgres pg_isready --timeout 10 -U postgres
  - docker ps -a

script:
  - docker run --net host -e CDC_POSTGRES_DSN_TEMPLATE='postgres://postgres@localhost:5432/{database}' --entrypoint python getsentry/cdc -m pytest
