services:
  - docker

install:
  - docker run -d --net host postgres:9.6 -c wal_level=logical -c max_replication_slots=1 -c max_wal_senders=1
  - docker build -t getsentry/cdc --target development .

script:
  - docker run --net host -e CDC_POSTGRES_DSN_TEMPLATE='postgres://@localhost:5432/{database}' --entrypoint python getsentry/cdc -m pytest