steps:
- name: 'gcr.io/kaniko-project/executor:v1.5.1'
  id: runtime-image
  args:
    [
      '--cache=true',
      '--build-arg',
      'SOURCE_COMMIT=$COMMIT_SHA',
      '--destination=us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
      '-f', './Dockerfile',
      '--target=application'
    ]
  timeout: 180s
# CDC end to end tests
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  env:
    - 'CDC_IMAGE=$$BASE_IMAGE:$COMMIT_SHA'
  args:
    - '-f'
    - 'docker-compose.gcb.yml'
    - run
    - '--rm'
    - cdc-e2e-test
# Clean up after tests
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args:
    - '-f'
    - 'docker-compose.gcb.yml'
    - down
    - '--rmi'
    - 'local'
    - '-v'
# Only tag "nightly" when on master
- name: 'gcr.io/cloud-builders/docker'
  secretEnv: ['DOCKER_PASSWORD']
  entrypoint: 'bash'
  args:
  - '-e'
  - '-c'
  - |
    # Only push to Docker Hub from master
    [ "$BRANCH_NAME" != "master" ] && exit 0
    docker pull $$BASE_IMAGE:$COMMIT_SHA 
    echo "$$DOCKER_PASSWORD" | docker login --username=sentrybuilder --password-stdin
    docker tag $$BASE_IMAGE:$COMMIT_SHA $PROJECT_ID/$REPO_NAME:$SHORT_SHA
    docker push $PROJECT_ID/$REPO_NAME:$SHORT_SHA
    docker tag $$BASE_IMAGE:$COMMIT_SHA $PROJECT_ID/$REPO_NAME:$COMMIT_SHA
    docker push $PROJECT_ID/$REPO_NAME:$COMMIT_SHA
    docker tag $$BASE_IMAGE:$COMMIT_SHA $PROJECT_ID/$REPO_NAME:nightly
    docker push $PROJECT_ID/$REPO_NAME:nightly
images:
  [
    "us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
  ]
timeout: 900s
options:
  env:
    - 'BASE_IMAGE=us.gcr.io/$PROJECT_ID/$REPO_NAME'
secrets:
- kmsKeyName: projects/sentryio/locations/global/keyRings/service-credentials/cryptoKeys/cloudbuild
  secretEnv:
    # This is a personal access token for the sentrybuilder account, encrypted using the
    # short guide at http://bit.ly/2Pg6uw9
    DOCKER_PASSWORD: |
      CiQAE8gN7y3OMxn+a1kofmK4Bi8jQZtdRFj2lYYwaZHVeIIBUzMSTQA9tvn8XCv2vqj6u8CHoeSP
      TVW9pLvSCorKoeNtOp0eb+6V1yNJW/+JC07DNO1KLbTbodbuza6jKJHU5xeAJ4kGQI78UY5Vu1Gp
      QcMK
