logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '%(asctime)s %(levelname)-8s %(message)s'
    handlers:
        stderr:
            class: 'logging.StreamHandler'
            formatter: 'simple'
    root:
        level: DEBUG
        handlers:
            - 'stderr'

source:
    commit_positions_after_flushed_messages: 1000
    commit_positions_after_seconds: 10.0
    backend:
        type: postgres_logical
        options:
            dsn: 'postgres://postgres@localhost:5432/postgres'
            slot:
                name: 'example'
                plugin: 'wal2json'
                create: true
                options:
                    include-xids: 'true'
                    write-in-chunks: 'true'
            keepalive_interval: 5.0

stream:
    backend:
        type: kafka
        options:
            topic: topic
            producer:
                bootstrap.servers: 'localhost:9092'
