source:
    backend:
        type: postgres_logical
        options:
            dsn: 'postgres://postgres@localhost:5432/pgbench'
            slot:
                name: 'pgbench'
                plugin: 'wal2json'
                create: true
                options:
                    include-xids: 'true'
                    include-timestamp: 'true'

producer:
    backend:
        type: kafka
        options:
            topic: topic
            options:
                bootstrap.servers: 'localhost:9092'
