source:
    backend:
        type: postgres_logical
        options:
            dsn: 'postgres://postgres@localhost:5432/postgres'
            slot:
                name: 'example'
                plugin: 'wal2json'
                options:
                    include-xids: 'true'
                    write-in-chunks: 'true'

producer:
    backend:
        type: kafka
        options:
            topic: topic
            options:
                bootstrap.servers: 'localhost:9092'
