version: 1

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '%(asctime)s %(levelname)-8s %(message)s'
    handlers:
        stderr:
            class: 'logging.StreamHandler'
            formatter: 'simple'
    root:
        level: DEBUG
        handlers:
            - 'stderr'

source:
    backend:
        type: postgres_logical
        options:
            dsn: 'postgres://postgres@sentry_postgres:5432/pgbench'
            slot:
                name: 'pgbench'
                plugin: 'test_decoding'
                create: true

snapshot:
    source:
        type: postgres
        options:
            dsn: 'postgres://postgres@sentry_postgres:5432/sentry'

producer:
    backend:
        type: kafka
        options:
            topic: topic
            options:
                bootstrap.servers: 'sentry_kafka:9093'

dogstatsd:
    host: localhost
    port: 8125
    message_sampling_rate: 0.1
    task_sampling_rate: 1.0

sentry:
    enabled: false
    dsn: 'http://KEY@host.docker.internal:8000/PROJECT'
