version: 1

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '%(asctime)s %(levelname)-8s %(message)s'
    handlers:
        stderr:
            class: 'logging.StreamHandler'
            formatter: 'simple'
    root:
        level: DEBUG
        handlers:
            - 'stderr'

source:
    backend:
        type: postgres_logical
        options:
            dsn: 'postgres://postgres@localhost:5432/sentry'
            slot:
                name: 'cdc'
                plugin: 'wal2json'
                create: true
                options:
                    include-xids: true
                    include-timestamp: true

snapshot:
    default_tables:
        - sentry_groupedmessage
    dump:
        type: file
        options:
            location: '/tmp/'

producer:
    backend:
        type: kafka
        options:
            topic: cdc
            options:
                bootstrap.servers: 'sentry_kafka:9093'

dogstatsd:
    host: localhost
    port: 8125
    message_sampling_rate: 0.1
    task_sampling_rate: 1.0

sentry:
    enabled: false
    dsn: 'http://05685163480d4e0c8e8b19e4b4740ce9@localhost:8000/2'
