version: 1

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '%(asctime)s %(levelname)-8s %(message)s'
    handlers:
        stderr:
            class: 'logging.StreamHandler'
            formatter: 'simple'
    root:
        level: DEBUG
        handlers:
            - 'stderr'

source:
    backend:
        type: postgres_logical
        options:
            dsn: 'postgres://postgres@sentry_postgres:5432/sentry'
            slot:
                name: 'cdc'
                parser: 'wal2json_parser_with_headers'
                plugin: 'wal2json'
                create: true
                options:
                    include-xids: 'true'
                    include-timestamp: 'true'
                    include-message-header: 'true'

snapshot:
    source:
        type: postgres
        options:
            dsn: 'postgres://postgres@sentry_postgres:5432/pgbench'
    control:
        producer:
            backend:
                type: kafka
                options:
                    topic: cdc_control
                    options:
                        bootstrap.servers: 'sentry_kafka:9092'

producer:
    backend:
        type: kafka
        options:
            topic: cdc
            options:
                bootstrap.servers: 'sentry_kafka:9093'

dogstatsd:
    host: host.docker.internal # I think, or wherever you have statsd if you have it
    port: 8125
    message_sampling_rate: 0.1
    task_sampling_rate: 1.0

sentry:
    enabled: false   # unless you want to enable sentry locally, then change the DSN below
    dsn: 'http://KEY@host.docker.internal:8000/PROJECT'
