version: 1

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '%(asctime)s %(levelname)-8s %(message)s'
    handlers:
        stderr:
            class: 'logging.StreamHandler'
            formatter: 'simple'
    root:
        level: DEBUG
        handlers:
            - 'stderr'

source:
    backend:
        type: postgres_logical
        options:
            dsn: 'postgres://postgres@localhost:5432/pgbench'
            slot:
                name: 'example'
                plugin: 'wal2json'
                options:
                    include-xids: 'true'
                    write-in-chunks: 'true'

producer:
    backend:
        type: kafka
        options:
            topic: topic
            options:
                bootstrap.servers: 'localhost:9092'
