version: 1

product: Snuba

destination:
    type: directory
    options:
        location: '/tmp/'

tables:
    -   table: sentry_groupedmessage
        columns:
            - id
            - status
            - last_seen
            - first_seen
            - active_at
            - first_release_id
    -   table: sentry_groupasignee
        columns:
            - id
            - project_id
            - group_id
            - user_id
