version: 1

product: snuba

destination:
    type: directory
    options:
        location: '/tmp/'

tables:
    -   table: sentry_groupasignee
        columns:
            - project_id
            - group_id            
            - date_added
            - user_id
            - team_id
