name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Run tests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Stop postgres
        run: |
          sudo service postgresql stop
      - name: Docker set up
        run: |
          docker run -e POSTGRES_PASSWORD=password -d --net host --name postgres $(docker build -q .github/workflows/postgres) -c wal_level=logical -c max_replication_slots=1 -c max_wal_senders=1
          docker build -t getsentry/cdc --target development .
          docker exec postgres pg_isready --timeout 10 -U postgres
          docker ps -a
      - name: Docker CDC tests
        run: |
          docker run --net host -e CDC_POSTGRES_DSN_TEMPLATE='postgres://postgres@localhost:5432/{database}' --entrypoint python getsentry/cdc -m pytest
